### ISSUE TITLE
Allow variables in pattern alternatives using union types

### ISSUE THREAD

**Issue by Lasering** [lampepfl/dotty-feature-requests#175] opened 2021-02-15 21:38 UTC
For the following ADT hierarchy:

```scala
sealed trait Foo
case object Empty extends Foo
case class JustList(list: List[Int]) extends Foo
case class PathAndList(path: String, list: List[Int]) extends Foo
```

The following code could compile:

```scala
val a: Foo = new JustList(List(1, 2, 3))
a match {
 case JustList(list) | PathAndList(_, list) => println(list)
 case Empty => println("Empty")
}
```

Where the variable `list` would type check to `List[Int] | List[Int]` which could be further reduced to `List[Int]`.
Currently the compiler issues the error `Illegal variable list in pattern alternative`.

The remaining scenarios could be type checked as follows:

-  `case JustList(list) | PathAndList(list, _) =>` would typecheck to `List[Int] | String`
-  `case JustList(list) | PathAndList(_, _) =>` would typecheck to `List[Int] | Null`

**Comment by smarter** [comment] 2021-02-15 21:47
Duplicate of https://github.com/lampepfl/dotty-feature-requests/issues/12

**Closed by smarter** 2021-02-15 21:47 UTC
