### ISSUE TITLE
automatically optimise loops over Range

### ISSUE THREAD

**Issue by strelec** [lampepfl/dotty-feature-requests#308] opened 2022-06-18 20:04 UTC
## Minimized code

```Scala
val range = 1 to 100 by 5
for (i <- range if f(x)) return i
```

## Expectation

For loops over a scala Range should desugar to a java for loop. This should be guaranteed by a spec, so programmers can rely on it.

Why?

1. I think programmers should have access to Java primitive building blocks to optimize tight loops (after doing a profiling of the runtime). Right now, only a while() statement is available, which forces you to use a mutable var, and that is not ideal.

2. JVM optimizer can do many optimizations on bare for loops (loop unswitching, loop peeling), that I think it cannot do on foreach with a lambda.

3. As the code is generated currently, returning from within a loop causes non local return with a large penalty.

4. Many places in the Scala collections library could be simplified (while loops could be rewritten to the new for loops).

Example of desugaring
```Java
for (int i = range.start; i <= range.end, i += range.step) {
   if (f(i)) return i
}
```

**Comment by SethTisue** [comment] 2022-06-20 23:38
corresponding Scala 2 ticket is https://github.com/scala/bug/issues/1338

**Comment by griggt** [comment] 2022-06-21 00:03
also https://github.com/lampepfl/dotty/issues/8880

**Comment by SethTisue** [comment] 2022-06-21 01:42
ah, seems like a straight-up duplicate of that one

**Comment by SethTisue** [comment] 2022-06-21 01:43
(hmm, neither "completed" or "not planned" seems like an appropriate closed status)

**Closed by SethTisue** 2022-06-21 01:42 UTC
Labels: area:performance
